const ADD_TODO = 'ADD_TODO'
const SET_NEW_TODO = 'SET_NEW_TODO'
const CLEAR_NEW_TODO = 'CLEAR_NEW_TODO'
const DELETE_TODO = 'DELETE_TODO'
const TOGGLE_TODO = 'TOGGLE_TODO'
const CLEAR_COMPLETED = 'CLEAR_COMPLETED'
const COMPLETE_ALL = 'COMPLETE_ALL'
const LOAD_TODOS = 'LOAD_TODOS'

export {
  ADD_TODO,
  SET_NEW_TODO,
  CLEAR_NEW_TODO,
  DELETE_TODO,
  TOGGLE_TODO,
  CLEAR_COMPLETED,
  COMPLETE_ALL,
  LOAD_TODOS
}
